server:
  port: 2010
spring:
  application:
    name: service-salarysetapi
  cloud:
    nacos:
      server-addr: 192.168.0.133:8848


  config:
    import:
        - nacos:service_salarysetapi.properties