spring:
  cloud:
    gateway:
      routes:
        - id: Employee-route
          uri: lb://service-employee
          predicates:
            - Path=/api/db/employee/**
        - id: User-route
          uri: lb://service-user
          predicates:
            - Path=/api/db/user/**
        - id: Department-route
          uri: lb://service-department
          predicates:
            - Path=/api/db/department/**
        - id: Position-route
          uri: lb://service-position
          predicates:
            - Path=/api/db/position/**
        - id: Modification-route
          uri: lb://service-modification
          predicates:
            - Path=/api/db/modification/**
        - id: Salary-route
          uri: lb://service-salary
          predicates:
            - Path=/api/db/salary/**
        - id: SalarySet-route
          uri: lb://service-salaryset
          predicates:
            - Path=/api/db/salaryset/**
        - id: Title-route
          uri: lb://service-title
          predicates:
            - Path=/api/db/title/**
        - id: Departmentapi-route
          uri: lb://service-departmentapi
          predicates:
            - Path=/api/department/**
        - id: Positionapi-route
          uri: lb://service-positionapi
          predicates:
            - Path=/api/position/**
        - id: Titleapi-route
          uri: lb://service-titleapi
          predicates:
            - Path=/api/title/**
        - id: Hrapi-route
          uri: lb://service-hrapi
          predicates:
            - Path=/api/hr/**
        - id: Salarysetapi-route
          uri: lb://service-salarysetapi
          predicates:
            - Path=/api/salaryset/**
        - id: Login-route
          uri: lb://service-login
          predicates:
            - Path=/auth/login
        - id: Register-route
          uri: lb://service-register
          predicates:
            - Path=/auth/register
        - id: Salaryapi-route
          uri: lb://service-salaryapi
          predicates:
            - Path=/api/salary/**
