server:
  port: 7001
spring:
  application:
    name: service-departmentapi
  cloud:
    nacos:
      server-addr: 192.168.0.133:8848


  config:
    import:
        - nacos:service_departmentapi.properties