server:
  port: 7002
spring:
  application:
    name: service-positionapi
  cloud:
    nacos:
      server-addr: 192.168.0.133:8848


  config:
    import:
        - nacos:service_positionapi.properties