server:
  port: 4000
spring:
  application:
    name: service-modification
  cloud:
    nacos:
      server-addr: 192.168.0.133:8848


  config:
    import:
        - nacos:service_modification.properties